name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "Your Name"
        git config user.email "your.email@example.com"

    - name: Add Remote for Repository 2
      run: git remote add repo2 https://github.com/kratoz6/Testing.git

    - name: Pull changes from Repository 2
      run: git pull repo2 main

    - name: Push changes to Repository 1
      run: git push origin main
